server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: MS-USER
          uri: lb://MS-USER
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: MS-USER
                fallbackuri: forward:/userServiceFallBack
        - id: MS-DEPARTMENT
          uri: lb://MS-DEPARTMENT
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: MS-DEPARTMENT
                fallbackuri: forward:/departmentServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true



