server:
  port: 9002

spring:
  application:
    name: MS-DEPARTMENT


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true
